%% Step_3b_windowToTarget_heatFlux_mapping.m
% Annular source model using the measured-support fixed Q_lm source map
%
% PURPOSE
%   - Read the fixed source map Q_parallel_full_lm (name kept for compatibility)
%   - Treat it as an annular source on a PLANE z = z_source
%   - Trace each annular patch to a PLANE target z = z_target
%   - Reconstruct plane-surface heat fluxes from mapped footprint area
%   - Plot the window-derived heat map projected along the flux tube at
%     the dump, helicon, and target axial planes
%
% IMPORTANT CONSISTENCY
%   - qTransferMode controls how Q_parallel_full_lm is interpreted:
%
%       preserve_step3_q_lm:
%         Q_lm is the trusted Step_3 q_window_lm scale
%         P_tube = Q_lm * A_lm
%
%       parallel_from_window_incidence:
%         Q_lm is interpreted as q_parallel_lm
%         P_tube = Q_lm * A_lm * sin(alpha_source)
%
% PLANE NORMALS
%   Since source and target are both planes at fixed z:
%
%       sin(alpha_source) = |Bz| / |B|
%       sin(alpha_t)      = |Bz| / |B|
%
% INPUT
%   1) bfield_protoMPEX_shotSeries_1.nc
%   2) fullSource_Qparallel.mat
%
% OUTPUT
%   trueAnnulusSource_toTarget_fromFullQparallel_output.nc
%
% -------------------------------------------------------------------------

clear; close all; clc;

%% ------------------------------------------------------------------------
% USER INPUTS
% -------------------------------------------------------------------------
profileFile = 'bfield_protoMPEX_shotSeries_1.nc';
sourceFile  = 'fullSource_Qparallel.mat';
outFile     = 'trueAnnulusSource_toTarget_fromFullQparallel_output.nc';

z_source = 1.75915;         % [m]
z_target = 4.140;           % [m]

z_projection_planes = [0.500, 1.754, z_target];  % [m]
z_projection_labels = {'Dump', 'Helicon', 'Target'};

dz_trace = 0.001;         % [m]
nStepsMax = 7000;
stop_if_outside_grid = true;

nXt = 320;
nYt = 320;

% Guard against stale source files generated by the older central-fill workflow.
% Current Step_3a leaves rows outside the measured window-connected radial
% support as NaN, so downstream power should not come from those rows.
enforceMeasuredRadialSupport = true;

makePlots = true;
makeTrajectoryPlot = false;  % legacy sparse source-to-target line plot
nTrajToPlot = 60;

makeFluxTube3DPlot = true;
maxTubesToPlot3D = 2000;
tubeSelectionMode3D = 'weighted';  % 'top', 'random', or 'weighted'
coilGeometryFile = 'protoMPEX_coil_setup.txt';
useExtrapolatedFieldForVisualization = true;

%% ------------------------------------------------------------------------
% STEP 0. LOAD MAGNETIC FIELD
% -------------------------------------------------------------------------
fprintf('Reading magnetic field: %s ...\n', profileFile);

r  = double(ncread(profileFile, 'r')); r = r(:);
z  = double(ncread(profileFile, 'z')); z = z(:);

Br = double(ncread(profileFile, 'br'));
Bt = double(ncread(profileFile, 'bt'));
Bz = double(ncread(profileFile, 'bz'));

nR = numel(r);
nZ = numel(z);

if ~isequal(size(Br), [nR, nZ])
    Br = permute(Br, [2 1]);
    Bt = permute(Bt, [2 1]);
    Bz = permute(Bz, [2 1]);
end

if z_source < min(z) || z_source > max(z)
    error('z_source is outside magnetic-field domain.');
end
if z_target < min(z) || z_target > max(z)
    error('z_target is outside magnetic-field domain.');
end
if numel(z_projection_labels) ~= numel(z_projection_planes)
    error('z_projection_labels must have one entry per z_projection_planes value.');
end
if any(z_projection_planes < min(z) | z_projection_planes > max(z))
    error('At least one requested projection plane is outside magnetic-field domain.');
end

FBr = griddedInterpolant({r, z}, Br, 'linear', 'none');
FBt = griddedInterpolant({r, z}, Bt, 'linear', 'none');
FBz = griddedInterpolant({r, z}, Bz, 'linear', 'none');

if useExtrapolatedFieldForVisualization
    FBr_viz = griddedInterpolant({r, z}, Br, 'linear', 'nearest');
    FBt_viz = griddedInterpolant({r, z}, Bt, 'linear', 'nearest');
    FBz_viz = griddedInterpolant({r, z}, Bz, 'linear', 'nearest');
    stop_if_outside_grid_viz = false;
else
    FBr_viz = FBr;
    FBt_viz = FBt;
    FBz_viz = FBz;
    stop_if_outside_grid_viz = stop_if_outside_grid;
end

%% ------------------------------------------------------------------------
% STEP 1. LOAD FIXED Q_lm SOURCE MAP
% -------------------------------------------------------------------------
fprintf('Reading %s ...\n', sourceFile);

S = load(sourceFile);

requiredVars = {'Q_parallel_full_lm','r_cent_full','r_edges_full', ...
                'theta_cent_deg','theta_edges_deg','A_full_lm'};
for k = 1:numel(requiredVars)
    if ~isfield(S, requiredVars{k})
        error('Missing variable %s in source file.', requiredVars{k});
    end
end

q_parallel_lm = double(S.Q_parallel_full_lm);
r_cent = double(S.r_cent_full(:));
r_edges = double(S.r_edges_full(:));
theta_cent_deg = double(S.theta_cent_deg(:)).';
theta_edges_deg = double(S.theta_edges_deg(:)).';
A_source_lm = double(S.A_full_lm);

qTransferMode_source = 'parallel_from_window_incidence';
if isfield(S, 'qTransferMode')
    qTransferMode_source = char(S.qTransferMode);
end

[nL, nM] = size(q_parallel_lm);

if numel(r_cent) ~= nL
    error('Length of r_cent_full does not match q_parallel_lm rows.');
end
if numel(theta_cent_deg) ~= nM
    error('Length of theta_cent_deg does not match q_parallel_lm columns.');
end

if enforceMeasuredRadialSupport && isfield(S, 'r_cent_in')
    r_cent_measured = double(S.r_cent_in(:));
    measuredRadialRows = r_cent >= min(r_cent_measured) & r_cent <= max(r_cent_measured);
    outsideMeasuredRows = ~measuredRadialRows;
    nOutsideFinite = nnz(isfinite(q_parallel_lm(outsideMeasuredRows,:)));

    if nOutsideFinite > 0
        sourcePowerBeforeMask = sum(q_parallel_lm(:) .* A_source_lm(:), 'omitnan');
        q_parallel_lm(outsideMeasuredRows,:) = NaN;
        sourcePowerAfterMask = sum(q_parallel_lm(:) .* A_source_lm(:), 'omitnan');

        warning(['Source file contains %d finite Q_lm bins outside the measured ', ...
                 'window-connected radial support. Masked them for target mapping; ', ...
                 'rerun Step_3a to refresh %s.'], nOutsideFinite, sourceFile);
        fprintf('[SOURCE MASK] sum(Q_lm*A_source): %.6e -> %.6e W-equivalent\n', ...
            sourcePowerBeforeMask, sourcePowerAfterMask);
    end
end

fprintf('Loaded fixed Q_lm source size = [%d x %d]\n', nL, nM);
fprintf('Source radial range = [%g, %g] m\n', min(r_edges), max(r_edges));
fprintf('qTransferMode = %s\n', qTransferMode_source);

%% ------------------------------------------------------------------------
% STEP 2. BUILD ANNULAR SOURCE PATCHES
% -------------------------------------------------------------------------
fprintf('Building annular source patches ...\n');

[THETA_LM_DEG, R_LM] = meshgrid(theta_cent_deg, r_cent);
THETA_LM_RAD = deg2rad(THETA_LM_DEG);

Xsrc_lm = R_LM .* cos(THETA_LM_RAD);
Ysrc_lm = R_LM .* sin(THETA_LM_RAD);

xsrc_c = NaN(nL, nM, 4);
ysrc_c = NaN(nL, nM, 4);
zsrc_c = NaN(nL, nM, 4);

for il = 1:nL
    r1 = r_edges(il);
    r2 = r_edges(il+1);

    for im = 1:nM
        th1 = theta_edges_deg(im);
        th2 = theta_edges_deg(im+1);

        rCorners  = [r1, r2, r2, r1];
        thCorners = [th1, th1, th2, th2];

        for ic = 1:4
            xsrc_c(il,im,ic) = rCorners(ic) * cosd(thCorners(ic));
            ysrc_c(il,im,ic) = rCorners(ic) * sind(thCorners(ic));
            zsrc_c(il,im,ic) = z_source;
        end
    end
end

%% ------------------------------------------------------------------------
% STEP 3. COMPUTE SOURCE POWER USING THE SAVED Q TRANSFER MODE
% -------------------------------------------------------------------------
fprintf('Computing source power from qTransferMode ...\n');

br_src = FBr(R_LM, z_source * ones(size(R_LM)));
bt_src = FBt(R_LM, z_source * ones(size(R_LM)));
bz_src = FBz(R_LM, z_source * ones(size(R_LM)));

Bmag_src = sqrt(br_src.^2 + bt_src.^2 + bz_src.^2);
Bmag_src(Bmag_src < 1e-12) = 1e-12;

sin_alpha_source = abs(bz_src) ./ Bmag_src;

switch lower(qTransferMode_source)
    case 'preserve_step3_q_lm'
        q_source_lm = q_parallel_lm;
        P_tube_lm = q_parallel_lm .* A_source_lm;
        A_perp_lm = A_source_lm;
        fprintf('Using Step_3-like power: P_tube = Q_lm * A_lm (no sin(alpha_source)).\n');

    case 'parallel_from_window_incidence'
        q_source_lm = q_parallel_lm .* sin_alpha_source;
        P_tube_lm = q_source_lm .* A_source_lm;
        A_perp_lm = A_source_lm .* sin_alpha_source;
        fprintf('Using parallel-flux power: P_tube = Q_parallel * A_lm * sin(alpha_source).\n');

    otherwise
        error('Unknown qTransferMode in %s: %s', sourceFile, qTransferMode_source);
end

fprintf('Finite Q_lm     = %d / %d\n', sum(isfinite(q_parallel_lm(:))), numel(q_parallel_lm));
fprintf('Max Q_lm        = %.6e W/m^2\n', max(q_parallel_lm(:), [], 'omitnan'));
fprintf('Max q_source_lm = %.6e W/m^2\n', max(q_source_lm(:), [], 'omitnan'));

%% ------------------------------------------------------------------------
% STEP 4. TRACE PATCH CENTERS TO TARGET
% -------------------------------------------------------------------------
fprintf('Tracing patch centers to target ...\n');

if makeTrajectoryPlot
    x_path = NaN(nL, nM, nStepsMax);
    y_path = NaN(nL, nM, nStepsMax);
    z_path = NaN(nL, nM, nStepsMax);
end

x_target_lm = NaN(nL, nM);
y_target_lm = NaN(nL, nM);
r_target_lm = NaN(nL, nM);
theta_target_deg_lm = NaN(nL, nM);

nPatches = nL * nM;
xhit_vec   = NaN(nPatches, 1);
yhit_vec   = NaN(nPatches, 1);
xpath_cell = cell(nPatches, 1);
ypath_cell = cell(nPatches, 1);
zpath_cell = cell(nPatches, 1);

R_vec         = R_LM(:);
THETA_vec     = THETA_LM_DEG(:);
doStorePath   = makeTrajectoryPlot;

parfor ii = 1:nPatches
    [ok, xhit, yhit, ~, xpath, ypath, zpath_] = trace_point_to_target( ...
        R_vec(ii), THETA_vec(ii), z_source, ...
        FBr, FBt, FBz, r, z, z_target, dz_trace, nStepsMax, stop_if_outside_grid);

    if ok
        xhit_vec(ii) = xhit;
        yhit_vec(ii) = yhit;
        if doStorePath
            xpath_cell{ii} = xpath;
            ypath_cell{ii} = ypath;
            zpath_cell{ii} = zpath_;
        end
    end
end

for ii = 1:nPatches
    if isfinite(xhit_vec(ii))
        [il, im] = ind2sub([nL, nM], ii);
        x_target_lm(il,im) = xhit_vec(ii);
        y_target_lm(il,im) = yhit_vec(ii);
        r_target_lm(il,im) = hypot(xhit_vec(ii), yhit_vec(ii));
        theta_target_deg_lm(il,im) = mod(atan2d(yhit_vec(ii), xhit_vec(ii)), 360);

        if makeTrajectoryPlot && ~isempty(xpath_cell{ii})
            ns = min(numel(xpath_cell{ii}), nStepsMax);
            x_path(il,im,1:ns) = xpath_cell{ii}(1:ns);
            y_path(il,im,1:ns) = ypath_cell{ii}(1:ns);
            z_path(il,im,1:ns) = zpath_cell{ii}(1:ns);
        end
    end
end

%% ------------------------------------------------------------------------
% STEP 5. TRACE PATCH CORNERS TO TARGET
% -------------------------------------------------------------------------
fprintf('Tracing patch corners to target ...\n');

xt_c = NaN(nL, nM, 4);
yt_c = NaN(nL, nM, 4);
zt_c = NaN(nL, nM, 4);
patch_ok = false(nL, nM);
fail_corner = NaN(nL, nM);

xt_c_flat  = NaN(nPatches, 4);
yt_c_flat  = NaN(nPatches, 4);
zt_c_flat  = NaN(nPatches, 4);
fail_flat  = NaN(nPatches, 1);

xsrc_flat = reshape(xsrc_c, nPatches, 4);
ysrc_flat = reshape(ysrc_c, nPatches, 4);
zsrc_flat = reshape(zsrc_c, nPatches, 4);

parfor ii = 1:nPatches
    ok_all = true;
    xhit_row = NaN(1, 4);
    yhit_row = NaN(1, 4);
    zhit_row = NaN(1, 4);
    fc = NaN;

    for ic = 1:4
        rc  = hypot(xsrc_flat(ii,ic), ysrc_flat(ii,ic));
        thc = mod(atan2d(ysrc_flat(ii,ic), xsrc_flat(ii,ic)), 360);
        zc  = zsrc_flat(ii,ic);

        [ok, xhit, yhit, zhit] = trace_point_to_target( ...
            rc, thc, zc, FBr, FBt, FBz, r, z, z_target, dz_trace, nStepsMax, stop_if_outside_grid);

        if ~ok
            ok_all = false;
            fc = ic;
            break;
        end

        xhit_row(ic) = xhit;
        yhit_row(ic) = yhit;
        zhit_row(ic) = zhit;
    end

    if ok_all
        xt_c_flat(ii,:) = xhit_row;
        yt_c_flat(ii,:) = yhit_row;
        zt_c_flat(ii,:) = zhit_row;
    else
        fail_flat(ii) = fc;
    end
end

for ii = 1:nPatches
    [il, im] = ind2sub([nL, nM], ii);
    if all(isfinite(xt_c_flat(ii,:)))
        xt_c(il,im,:) = xt_c_flat(ii,:);
        yt_c(il,im,:) = yt_c_flat(ii,:);
        zt_c(il,im,:) = zt_c_flat(ii,:);
        patch_ok(il,im) = true;
    else
        fail_corner(il,im) = fail_flat(ii);
    end
end

fprintf('Mapped target patches = %d / %d\n', nnz(patch_ok), numel(patch_ok));
fprintf('Mapped target patches by l band:\n');
disp(sum(patch_ok,2));

%% ------------------------------------------------------------------------
% STEP 6. COMPUTE TARGET SURFACE HEAT FLUX  (flux-tube volume method)
% -------------------------------------------------------------------------
% Each flux tube carries the fixed power P_tube computed from qTransferMode.
% As the tube cross-section changes along the field line (magnetic
% compression / expansion), the local heat flux at the target is:
%
%   q_target = P_tube / A_target_polygon
%
% where A_target_polygon is the flat-plane area of the mapped quadrilateral
% footprint, computed via the shoelace formula on the 4 traced corners.
% This automatically conserves energy and captures flux-tube volume changes
% without requiring an explicit B-field ratio.
%
% sin(alpha_target) is also evaluated at the patch centre (for reference
% and to be saved in the output file).
%
fprintf('Computing q_target_lm (flux-tube volume method) ...\n');

A_target_lm = NaN(nL, nM);
q_target_lm = NaN(nL, nM);

for il = 1:nL
    for im = 1:nM
        if ~patch_ok(il,im) || ~isfinite(P_tube_lm(il,im))
            continue;
        end

        xv = squeeze(xt_c(il,im,:));
        yv = squeeze(yt_c(il,im,:));

        if any(~isfinite(xv)) || any(~isfinite(yv))
            continue;
        end

        % Shoelace formula for quadrilateral area in the flat target plane
        nv = numel(xv);
        A_poly = 0;
        for kv = 1:nv
            kn = mod(kv, nv) + 1;
            A_poly = A_poly + xv(kv)*yv(kn) - xv(kn)*yv(kv);
        end
        A_poly = 0.5 * abs(A_poly);

        if A_poly < 1e-12
            continue;
        end

        A_target_lm(il,im) = A_poly;
        q_target_lm(il,im) = P_tube_lm(il,im) / A_poly;
    end
end

% Diagnostic: B-based incidence angle at target centre (not applied to q_target)
sin_alpha_t = NaN(nL, nM);
Bmag_tgt_lm = NaN(nL, nM);

for il = 1:nL
    for im = 1:nM
        if ~isfinite(r_target_lm(il,im))
            continue;
        end

        br_t = FBr(r_target_lm(il,im), z_target);
        bt_t = FBt(r_target_lm(il,im), z_target);
        bz_t = FBz(r_target_lm(il,im), z_target);

        if any(~isfinite([br_t, bt_t, bz_t]))
            continue;
        end

        bmag_t = sqrt(br_t^2 + bt_t^2 + bz_t^2);
        if bmag_t < 1e-12
            continue;
        end

        sin_alpha_t(il,im) = abs(bz_t) / bmag_t;
        Bmag_tgt_lm(il,im) = bmag_t;
    end
end

B_ratio_diag = Bmag_tgt_lm ./ Bmag_src;
fprintf('[DIAG] |B_target|/|B_source| (mirror factor, not applied): min=%.3f  median=%.3f  max=%.3f\n', ...
    min(B_ratio_diag(:),[],'omitnan'), median(B_ratio_diag(:),'omitnan'), max(B_ratio_diag(:),[],'omitnan'));
fprintf('[DIAG] sin(alpha_target): min=%.4f  median=%.4f  max=%.4f\n', ...
    min(sin_alpha_t(:),[],'omitnan'), median(sin_alpha_t(:),'omitnan'), max(sin_alpha_t(:),[],'omitnan'));
fprintf('[DIAG] A_target_lm [m^2]: min=%.4e  median=%.4e  max=%.4e\n', ...
    min(A_target_lm(:),[],'omitnan'), median(A_target_lm(:),'omitnan'), max(A_target_lm(:),[],'omitnan'));
fprintf('[DIAG] q_target_lm [W/m^2]: min=%.4e  median=%.4e  max=%.4e\n', ...
    min(q_target_lm(:),[],'omitnan'), median(q_target_lm(:),'omitnan'), max(q_target_lm(:),[],'omitnan'));
fprintf('[DIAG] q_sinAlpha (comparison only) = Q_lm * sin(alpha_t): max=%.4e W/m^2\n', ...
    max(q_parallel_lm(:) .* sin_alpha_t(:),[],'omitnan'));

%% ------------------------------------------------------------------------
% STEP 7. RASTERIZE TARGET PATCH POLYGONS
% -------------------------------------------------------------------------
fprintf('Rasterizing target polygons ...\n');

xmin = min(xt_c(:), [], 'omitnan');
xmax = max(xt_c(:), [], 'omitnan');
ymin = min(yt_c(:), [], 'omitnan');
ymax = max(yt_c(:), [], 'omitnan');

pad = 0.002;
xt_grid = linspace(xmin-pad, xmax+pad, nXt);
yt_grid = linspace(ymin-pad, ymax+pad, nYt);
[XTG, YTG] = meshgrid(xt_grid, yt_grid);

q_target_sum   = zeros(nYt, nXt);
q_target_count = zeros(nYt, nXt);
P_target_sum   = zeros(nYt, nXt);

for il = 1:nL
    for im = 1:nM
        if ~patch_ok(il,im) || ~isfinite(q_target_lm(il,im))
            continue;
        end

        xv = squeeze(xt_c(il,im,:));
        yv = squeeze(yt_c(il,im,:));

        in = inpolygon(XTG, YTG, xv, yv);

        q_target_sum(in)   = q_target_sum(in) + q_target_lm(il,im);
        q_target_count(in) = q_target_count(in) + 1;
        P_target_sum(in)   = P_target_sum(in) + P_tube_lm(il,im);
    end
end

q_target_map = NaN(nYt, nXt);
mask = q_target_count > 0;
q_target_map(mask) = q_target_sum(mask) ./ q_target_count(mask);

%% ------------------------------------------------------------------------
% STEP 8. BUILD REQUESTED AXIAL PROJECTION HEATMAPS
% -------------------------------------------------------------------------
fprintf('Building flux-tube projection heatmaps at requested z planes ...\n');

nProjectionPlanes = numel(z_projection_planes);
projectionMaps = struct('label', {}, 'z', {}, 'x_grid', {}, 'y_grid', {}, ...
                        'q_map', {}, 'q_lm', {}, 'A_lm', {}, ...
                        'patch_ok', {}, 'x_c', {}, 'y_c', {}, ...
                        'fallback_mode', {});

q_center_projection_lm = q_source_lm;
if ~any(isfinite(q_center_projection_lm(:)))
    q_center_projection_lm = q_parallel_lm;
end

for ip = 1:nProjectionPlanes
    z_plane = z_projection_planes(ip);
    fprintf('  %s plane: z = %.6f m ...\n', z_projection_labels{ip}, z_plane);
    fallback_mode = 'polygon';

    if abs(z_plane - z_target) < 1e-9
        x_plane_c = xt_c;
        y_plane_c = yt_c;
        patch_ok_plane = patch_ok;
        A_plane_lm = A_target_lm;
        q_plane_lm = q_target_lm;
    else
        [x_plane_c, y_plane_c, ~, patch_ok_plane] = trace_patch_corners_to_plane( ...
            xsrc_c, ysrc_c, zsrc_c, z_plane, ...
            FBr, FBt, FBz, r, z, dz_trace, nStepsMax, stop_if_outside_grid);

        [A_plane_lm, q_plane_lm] = compute_plane_heat_flux_lm( ...
            x_plane_c, y_plane_c, patch_ok_plane, P_tube_lm);
    end

    [x_plane_grid, y_plane_grid, q_plane_map] = rasterize_plane_heat_flux_map( ...
        x_plane_c, y_plane_c, patch_ok_plane, q_plane_lm, nXt, nYt, pad);

    if ~any(isfinite(q_plane_map(:))) && useExtrapolatedFieldForVisualization && ...
       abs(z_plane - z_target) >= 1e-9
        warning('%s z = %.6f m polygon heat map is empty; retrying with visualization-only nearest-extrapolated B field.', ...
            z_projection_labels{ip}, z_plane);

        [x_plane_c, y_plane_c, ~, patch_ok_plane] = trace_patch_corners_to_plane( ...
            xsrc_c, ysrc_c, zsrc_c, z_plane, ...
            FBr_viz, FBt_viz, FBz_viz, r, z, dz_trace, nStepsMax, stop_if_outside_grid_viz);

        [A_plane_lm, q_plane_lm] = compute_plane_heat_flux_lm( ...
            x_plane_c, y_plane_c, patch_ok_plane, P_tube_lm);

        [x_plane_grid, y_plane_grid, q_plane_map] = rasterize_plane_heat_flux_map( ...
            x_plane_c, y_plane_c, patch_ok_plane, q_plane_lm, nXt, nYt, pad);

        fallback_mode = 'polygon_nearest_extrapolated_B';
    end

    if ~any(isfinite(q_plane_map(:))) && abs(z_plane - z_target) >= 1e-9
        warning('%s z = %.6f m polygon heat map is still empty; using centerline-scattered heat map fallback.', ...
            z_projection_labels{ip}, z_plane);

        [x_plane_grid, y_plane_grid, q_plane_map, q_plane_lm, patch_ok_plane, ...
            x_center_lm, y_center_lm] = rasterize_centerline_projection_heat_map( ...
                R_LM, THETA_LM_DEG, z_source, z_plane, ...
                FBr_viz, FBt_viz, FBz_viz, r, z, dz_trace, nStepsMax, ...
                stop_if_outside_grid_viz, q_center_projection_lm, nXt, nYt, pad);

        x_plane_c = repmat(x_center_lm, 1, 1, 4);
        y_plane_c = repmat(y_center_lm, 1, 1, 4);
        A_plane_lm = NaN(size(q_plane_lm));
        fallback_mode = 'centerline_scattered';
    end

    projectionMaps(ip).label = z_projection_labels{ip};
    projectionMaps(ip).z = z_plane;
    projectionMaps(ip).x_grid = x_plane_grid;
    projectionMaps(ip).y_grid = y_plane_grid;
    projectionMaps(ip).q_map = q_plane_map;
    projectionMaps(ip).q_lm = q_plane_lm;
    projectionMaps(ip).A_lm = A_plane_lm;
    projectionMaps(ip).patch_ok = patch_ok_plane;
    projectionMaps(ip).x_c = x_plane_c;
    projectionMaps(ip).y_c = y_plane_c;
    projectionMaps(ip).fallback_mode = fallback_mode;

    fprintf('    mapped patches = %d / %d, max q_map = %.6e W/m^2, mode = %s\n', ...
        nnz(patch_ok_plane), numel(patch_ok_plane), max(q_plane_map(:), [], 'omitnan'), ...
        fallback_mode);
end

%% ------------------------------------------------------------------------
% STEP 9. TRACE SELECTED 3D FLUX TUBES FOR PLOTTING
% -------------------------------------------------------------------------
if makeFluxTube3DPlot
    fprintf('Tracing selected 3D flux tubes in Step_3c style ...\n');

    z_flux_start = min(z_projection_planes);
    z_flux_end = max(z_projection_planes);

    q_fluxTubeColor_lm = q_source_lm;
    if ~any(isfinite(q_fluxTubeColor_lm(:)))
        q_fluxTubeColor_lm = q_parallel_lm;
    end

    validFluxTubeMask = isfinite(q_fluxTubeColor_lm) & isfinite(P_tube_lm) & ...
                        isfinite(R_LM) & isfinite(THETA_LM_DEG);
    idx_valid_flux = find(validFluxTubeMask);

    if isempty(idx_valid_flux)
        warning('No valid flux-tube centers available for the 3D plot.');
        idx_trace_flux = [];
        q_trace_flux = [];
        x_path_all = {};
        y_path_all = {};
        z_path_all = {};
        r_path_all = {};
    else
        idx_trace_flux = select_flux_tube_indices( ...
            idx_valid_flux, q_fluxTubeColor_lm(:), maxTubesToPlot3D, tubeSelectionMode3D);

        nTraceFlux = numel(idx_trace_flux);
        q_trace_flux = q_fluxTubeColor_lm(idx_trace_flux);

        x_path_all = cell(nTraceFlux, 1);
        y_path_all = cell(nTraceFlux, 1);
        z_path_all = cell(nTraceFlux, 1);
        r_path_all = cell(nTraceFlux, 1);

        R_trace = R_LM(idx_trace_flux);
        THETA_trace = THETA_LM_DEG(idx_trace_flux);

        for it = 1:nTraceFlux
            [ok, x_path_i, y_path_i, z_path_i, r_path_i] = trace_flux_tube_between_planes( ...
                R_trace(it), THETA_trace(it), z_source, z_flux_start, z_flux_end, ...
                FBr_viz, FBt_viz, FBz_viz, r, z, dz_trace, nStepsMax, ...
                stop_if_outside_grid_viz);

            if ok
                x_path_all{it} = x_path_i;
                y_path_all{it} = y_path_i;
                z_path_all{it} = z_path_i;
                r_path_all{it} = r_path_i;
            end
        end

        fprintf('Selected 3D flux tubes = %d; traced full dump-to-target paths = %d\n', ...
            nTraceFlux, nnz(~cellfun(@isempty, x_path_all)));
    end
end

%% ------------------------------------------------------------------------
% STEP 10. DIAGNOSTICS
% -------------------------------------------------------------------------
fprintf('Finite q_target_lm = %d / %d\n', sum(isfinite(q_target_lm(:))), numel(q_target_lm));
fprintf('Max q_target_lm    = %.6e W/m^2\n', max(q_target_lm(:), [], 'omitnan'));
fprintf('Max q_target_map   = %.6e W/m^2\n', max(q_target_map(:), [], 'omitnan'));

fprintf('Target radius range by row:\n');
for il = 1:nL
    fprintf('row %d: min=%g max=%g mean=%g\n', il, ...
        min(r_target_lm(il,:), [], 'omitnan'), ...
        max(r_target_lm(il,:), [], 'omitnan'), ...
        mean(r_target_lm(il,:), 'omitnan'));
end

% ---- Power conservation check ----
P_source_total = sum(P_tube_lm(:), 'omitnan');

% Tube-level: exact by construction (q_target x A_target = P_tube per tube)
P_tube_level = sum(q_target_lm(:) .* A_target_lm(:), 'omitnan');

% Rasterized: approximate (depends on pixel coverage and overlap averaging)
dA_target = (xt_grid(2)-xt_grid(1)) * (yt_grid(2)-yt_grid(1));
P_target_total = sum(q_target_map(:), 'omitnan') * dA_target;

fprintf('\n--- Power conservation check ---\n');
fprintf('Source tube power (sum P_tube)            = %.4e W\n', P_source_total);
fprintf('Target tube-level (sum q_tgt x A_tgt)     = %.4e W  (should equal source)\n', P_tube_level);
fprintf('Target rasterized (sum q_map x dA_pixel)  = %.4e W\n', P_target_total);
if P_source_total > 0
    fprintf('Tube-level ratio   P_tube_tgt / P_src    = %.4f\n', P_tube_level / P_source_total);
    fprintf('Rasterized ratio   P_rast_tgt / P_src    = %.3f\n', P_target_total / P_source_total);
    if abs(P_target_total/P_source_total - 1) > 0.2
        warning('Rasterized power imbalance > 20%%. Check rasterization grid coverage.');
    end
end
if strcmpi(qTransferMode_source, 'parallel_from_window_incidence')
    fprintf('Max Q_lm / max q_source_lm ratio = %.2f\n', ...
        max(q_parallel_lm(:),[],'omitnan') / max(q_source_lm(:),[],'omitnan'));
end

%% ------------------------------------------------------------------------
% STEP 11. PLOTS
% -------------------------------------------------------------------------
if makePlots
    figure('Color','w','Position',[100 100 1100 420]);

    subplot(1,2,1);
    imagesc(theta_cent_deg, r_cent, q_parallel_lm);
    set(gca,'YDir','normal');
    xlabel('\theta [deg]');
    ylabel('source annulus radius [m]');
    title('Fixed source Q_{lm}');
    colorbar;

    subplot(1,2,2);
    imagesc(theta_cent_deg, r_cent, q_source_lm);
    set(gca,'YDir','normal');
    xlabel('\theta [deg]');
    ylabel('source annulus radius [m]');
    title('Source-plane surface heat flux q_{source,lm}');
    colorbar;

    figure('Color','w');
    hold on;
    for il = 1:nL
        for im = 1:nM
            xv = squeeze(xsrc_c(il,im,:));
            yv = squeeze(ysrc_c(il,im,:));
            if all(isfinite(xv))
                patch(xv, yv, q_source_lm(il,im), 'EdgeColor', 'none');
            end
        end
    end
    axis equal;
    xlabel('x source [m]');
    ylabel('y source [m]');
    title('Annular source patches');
    colorbar;
    view(2);

    figure('Color','w');
    imagesc(theta_cent_deg, r_cent, patch_ok);
    set(gca,'YDir','normal');
    xlabel('\theta [deg]');
    ylabel('source annulus radius [m]');
    title('patch\_ok map');
    colorbar;

    figure('Color','w');
    imagesc(theta_cent_deg, r_cent, fail_corner);
    set(gca,'YDir','normal');
    xlabel('\theta [deg]');
    ylabel('source annulus radius [m]');
    title('first failed corner index');
    colorbar;

    figure('Color','w');
    imagesc(theta_cent_deg, r_cent, r_target_lm);
    set(gca,'YDir','normal');
    xlabel('\theta [deg]');
    ylabel('source annulus radius [m]');
    title('Mapped target radius r_T(l,m)');
    colorbar;

    figure('Color','w');
    hold on;
    for il = 1:nL
        for im = 1:nM
            if ~patch_ok(il,im) || ~isfinite(q_target_lm(il,im))
                continue;
            end
            xv = squeeze(xt_c(il,im,:));
            yv = squeeze(yt_c(il,im,:));
            patch(xv, yv, q_target_lm(il,im), 'EdgeColor', 'none');
        end
    end
    axis equal;
    xlabel('x target [m]');
    ylabel('y target [m]');
    title('Connected target patches q_{target,lm}');
    colorbar;
    view(2);

    figure('Color','w');
    imagesc(xt_grid, yt_grid, q_target_map);
    set(gca,'YDir','normal');
    axis equal tight;
    xlabel('x target [m]');
    ylabel('y target [m]');
    title('Continuous rasterized target heat-flux map');
    colorbar;

    projectionQValues = [];
    xProjectionLimits = [Inf, -Inf];
    yProjectionLimits = [Inf, -Inf];
    for ip = 1:nProjectionPlanes
        qv = projectionMaps(ip).q_map(:);
        projectionQValues = [projectionQValues; qv(isfinite(qv))]; %#ok<AGROW>
        xProjectionLimits(1) = min(xProjectionLimits(1), min(projectionMaps(ip).x_grid));
        xProjectionLimits(2) = max(xProjectionLimits(2), max(projectionMaps(ip).x_grid));
        yProjectionLimits(1) = min(yProjectionLimits(1), min(projectionMaps(ip).y_grid));
        yProjectionLimits(2) = max(yProjectionLimits(2), max(projectionMaps(ip).y_grid));
    end

    if isempty(projectionQValues)
        projectionColorMax = 1;
    else
        projectionColorMax = max(projectionQValues);
    end

    if any(~isfinite([xProjectionLimits, yProjectionLimits])) || ...
       xProjectionLimits(2) <= xProjectionLimits(1) || ...
       yProjectionLimits(2) <= yProjectionLimits(1)
        xProjectionLimits = [-0.1, 0.1];
        yProjectionLimits = [-0.1, 0.1];
    end

    figure('Color','w','Position',[80 80 1450 440]);
    for ip = 1:nProjectionPlanes
        subplot(1, nProjectionPlanes, ip);
        imagesc(projectionMaps(ip).x_grid, projectionMaps(ip).y_grid, projectionMaps(ip).q_map);
        set(gca,'YDir','normal');
        axis equal;
        xlim(xProjectionLimits);
        ylim(yProjectionLimits);
        if isfinite(projectionColorMax) && projectionColorMax > 0
            caxis([0 projectionColorMax]);
        end
        xlabel('x [m]');
        ylabel('y [m]');
        titleText = sprintf('%s z = %.3f m', projectionMaps(ip).label, projectionMaps(ip).z);
        if ~strcmpi(projectionMaps(ip).fallback_mode, 'polygon')
            titleText = sprintf('%s (%s)', titleText, projectionMaps(ip).fallback_mode);
        end
        title(titleText, 'Interpreter', 'none');
        colorbar;
    end
    colormap(gcf, parula);
    if exist('sgtitle', 'file')
        sgtitle('Window heat map projected along flux tube');
    end

    if makeFluxTube3DPlot && exist('x_path_all','var')
        plot_mpex_flux_tubes_3D( ...
            x_path_all, y_path_all, z_path_all, q_trace_flux, ...
            z_projection_planes, z_projection_labels, z_source, z_target, ...
            coilGeometryFile);
    end

    if makeTrajectoryPlot && exist('x_path','var')
        figure('Color','w');
        hold on;
        count = 0;
        for il = 1:nL
            for im = 1:nM
                xx = squeeze(x_path(il,im,:));
                yy = squeeze(y_path(il,im,:));
                zz = squeeze(z_path(il,im,:));
                good = isfinite(xx) & isfinite(yy) & isfinite(zz);
                if any(good)
                    plot3(xx(good), yy(good), zz(good), 'LineWidth', 1.0);
                    count = count + 1;
                end
                if count >= nTrajToPlot
                    break;
                end
            end
            if count >= nTrajToPlot
                break;
            end
        end
        xlabel('x [m]');
        ylabel('y [m]');
        zlabel('z [m]');
        title('Connected source-to-target flux-tube trajectories');
        grid on;
        axis equal;
        view(3);
    end
end

%% ------------------------------------------------------------------------
% STEP 12. SAVE OUTPUT
% -------------------------------------------------------------------------
fprintf('Writing %s ...\n', outFile);

if exist(outFile, 'file')
    delete(outFile);
end

nccreate(outFile, 'r', 'Dimensions', {'r', nR});
nccreate(outFile, 'z', 'Dimensions', {'z', nZ});
nccreate(outFile, 'theta_cent_deg', 'Dimensions', {'m', nM});
nccreate(outFile, 'r_cent', 'Dimensions', {'l', nL});

nccreate(outFile, 'q_parallel_lm', 'Dimensions', {'l', nL, 'm', nM});
nccreate(outFile, 'q_source_lm', 'Dimensions', {'l', nL, 'm', nM});
nccreate(outFile, 'sin_alpha_source', 'Dimensions', {'l', nL, 'm', nM});
nccreate(outFile, 'P_tube_lm', 'Dimensions', {'l', nL, 'm', nM});
nccreate(outFile, 'A_source_lm', 'Dimensions', {'l', nL, 'm', nM});
nccreate(outFile, 'A_perp_lm', 'Dimensions', {'l', nL, 'm', nM});

nccreate(outFile, 'q_target_lm', 'Dimensions', {'l', nL, 'm', nM});
nccreate(outFile, 'A_target_lm', 'Dimensions', {'l', nL, 'm', nM});
nccreate(outFile, 'sin_alpha_t', 'Dimensions', {'l', nL, 'm', nM});
nccreate(outFile, 'q_target_map', 'Dimensions', {'y_t', nYt, 'x_t', nXt});
nccreate(outFile, 'xt_grid', 'Dimensions', {'x_t', nXt});
nccreate(outFile, 'yt_grid', 'Dimensions', {'y_t', nYt});

ncwrite(outFile, 'r', r);
ncwrite(outFile, 'z', z);
ncwrite(outFile, 'theta_cent_deg', theta_cent_deg);
ncwrite(outFile, 'r_cent', r_cent);

ncwrite(outFile, 'q_parallel_lm', q_parallel_lm);
ncwrite(outFile, 'q_source_lm', q_source_lm);
ncwrite(outFile, 'sin_alpha_source', sin_alpha_source);
ncwrite(outFile, 'P_tube_lm', P_tube_lm);
ncwrite(outFile, 'A_source_lm', A_source_lm);
ncwrite(outFile, 'A_perp_lm', A_perp_lm);

ncwrite(outFile, 'q_target_lm', q_target_lm);
ncwrite(outFile, 'A_target_lm', A_target_lm);
ncwrite(outFile, 'sin_alpha_t', sin_alpha_t);
ncwrite(outFile, 'q_target_map', q_target_map);
ncwrite(outFile, 'xt_grid', xt_grid);
ncwrite(outFile, 'yt_grid', yt_grid);

fprintf('Done.\n');

%% ========================================================================
% LOCAL FUNCTION
% ========================================================================
function [ok, xhit, yhit, zhit, xpath, ypath, zpath_] = trace_point_to_target( ...
    r0, th0_deg, z0, FBr, FBt, FBz, r_grid, z_grid, z_target, dz_trace, nStepsMax, stop_if_outside_grid)

    ok = false;
    xhit = NaN; yhit = NaN; zhit = NaN;
    xpath = NaN(1, nStepsMax);
    ypath = NaN(1, nStepsMax);
    zpath_ = NaN(1, nStepsMax);

    r_now = r0;
    th_now_deg = th0_deg;
    z_now = z0;

    xpath(1) = r_now * cosd(th_now_deg);
    ypath(1) = r_now * sind(th_now_deg);
    zpath_(1) = z_now;

    step_sign = sign(z_target - z_now);
    if step_sign == 0
        xhit = r_now * cosd(th_now_deg);
        yhit = r_now * sind(th_now_deg);
        zhit = z_now;
        ok = true;
        return;
    end

    dz_local = step_sign * abs(dz_trace);

    for is = 2:nStepsMax
        br_now = FBr(r_now, z_now);
        bt_now = FBt(r_now, z_now);
        bz_now = FBz(r_now, z_now);

        if any(~isfinite([br_now, bt_now, bz_now])) || abs(bz_now) < 1e-12
            return;
        end

        dr_dz = br_now / bz_now;
        dtheta_dz_rad = bt_now / max(r_now, 1e-8) / bz_now;

        r_next = r_now + dr_dz * dz_local;
        th_next_deg = mod(th_now_deg + rad2deg(dtheta_dz_rad * dz_local), 360);
        z_next = z_now + dz_local;

        crossed = (step_sign > 0 && z_now < z_target && z_next >= z_target) || ...
                  (step_sign < 0 && z_now > z_target && z_next <= z_target);

        if crossed
            f = (z_target - z_now) / (z_next - z_now);
            r_hit = r_now + f * (r_next - r_now);
            dth_hit = mod(th_next_deg - th_now_deg + 180, 360) - 180;
            th_hit = mod(th_now_deg + f * dth_hit, 360);

            xhit = r_hit * cosd(th_hit);
            yhit = r_hit * sind(th_hit);
            zhit = z_target;

            xpath(is) = xhit;
            ypath(is) = yhit;
            zpath_(is) = zhit;
            ok = true;
            return;
        end

        if stop_if_outside_grid
            if r_next < min(r_grid) || r_next > max(r_grid) || ...
               z_next < min(z_grid) || z_next > max(z_grid)
                return;
            end
        end

        r_now = r_next;
        th_now_deg = th_next_deg;
        z_now = z_next;

        xpath(is) = r_now * cosd(th_now_deg);
        ypath(is) = r_now * sind(th_now_deg);
        zpath_(is) = z_now;
    end
end

function idx_trace = select_flux_tube_indices(idx_valid, q_values, maxN, mode)

    idx_valid = idx_valid(:);

    if numel(idx_valid) <= maxN
        idx_trace = idx_valid;
        return;
    end

    mode = lower(char(mode));

    switch mode
        case 'top'
            [~, order] = sort(q_values(idx_valid), 'descend');
            idx_trace = idx_valid(order(1:maxN));

        case 'random'
            rng(1);
            order = randperm(numel(idx_valid), maxN);
            idx_trace = idx_valid(order);

        case 'weighted'
            nTop = round(0.45 * maxN);
            nRand = maxN - nTop;

            [~, orderTop] = sort(q_values(idx_valid), 'descend');
            idx_top = idx_valid(orderTop(1:nTop));

            remaining = setdiff(idx_valid, idx_top);
            rng(1);

            if numel(remaining) > nRand
                idx_rand = remaining(randperm(numel(remaining), nRand));
            else
                idx_rand = remaining;
            end

            idx_trace = [idx_top(:); idx_rand(:)];

        otherwise
            error('Unknown tubeSelectionMode3D: %s', mode);
    end
end

function [ok, x_path, y_path, z_path, r_path] = trace_flux_tube_between_planes( ...
    r0, th0_deg, z0, z_start, z_end, FBr, FBt, FBz, r_grid, z_grid, ...
    dz_trace, nStepsMax, stop_if_outside_grid)

    ok = false;
    x_path = [];
    y_path = [];
    z_path = [];
    r_path = [];

    [ok_back, ~, ~, ~, x_back, y_back, z_back] = trace_point_to_target( ...
        r0, th0_deg, z0, FBr, FBt, FBz, r_grid, z_grid, z_start, ...
        dz_trace, nStepsMax, stop_if_outside_grid);

    [ok_fwd, ~, ~, ~, x_fwd, y_fwd, z_fwd] = trace_point_to_target( ...
        r0, th0_deg, z0, FBr, FBt, FBz, r_grid, z_grid, z_end, ...
        dz_trace, nStepsMax, stop_if_outside_grid);

    if ~ok_back || ~ok_fwd
        return;
    end

    good_back = isfinite(x_back) & isfinite(y_back) & isfinite(z_back);
    good_fwd = isfinite(x_fwd) & isfinite(y_fwd) & isfinite(z_fwd);

    if nnz(good_back) < 2 || nnz(good_fwd) < 2
        return;
    end

    x_back = x_back(good_back);
    y_back = y_back(good_back);
    z_back = z_back(good_back);

    x_fwd = x_fwd(good_fwd);
    y_fwd = y_fwd(good_fwd);
    z_fwd = z_fwd(good_fwd);

    x_fwd = x_fwd(:);
    y_fwd = y_fwd(:);
    z_fwd = z_fwd(:);

    x_path = [flipud(x_back(:)); x_fwd(2:end)];
    y_path = [flipud(y_back(:)); y_fwd(2:end)];
    z_path = [flipud(z_back(:)); z_fwd(2:end)];

    x_path = x_path(:);
    y_path = y_path(:);
    z_path = z_path(:);
    r_path = hypot(x_path, y_path);

    ok = true;
end

function plot_mpex_flux_tubes_3D( ...
    x_path_all, y_path_all, z_path_all, q_trace, ...
    z_projection_planes, z_projection_labels, z_source, z_target, coilGeometryFile)

    if isempty(x_path_all) || isempty(q_trace) || ~any(isfinite(q_trace))
        warning('Skipping 3D flux-tube plot because no traced tubes have finite heat-flux values.');
        return;
    end

    cmap = get_heat_colormap(256);
    qmin = min(q_trace(:), [], 'omitnan');
    qmax = max(q_trace(:), [], 'omitnan');

    if ~isfinite(qmin) || ~isfinite(qmax)
        warning('Skipping 3D flux-tube plot because color limits are not finite.');
        return;
    end

    figure('Color','w','Position',[60 60 1500 900]);
    hold on;
    grid on;
    box on;

    geom = plot_mpex_device_3D(coilGeometryFile, z_projection_planes, z_projection_labels);

    plot3([0 0], [0 0], [min(z_projection_planes) max(z_projection_planes)], ...
        'k--', 'LineWidth', 1.0);

    for it = 1:numel(x_path_all)
        if isempty(x_path_all{it})
            continue;
        end

        ci = color_index(q_trace(it), qmin, qmax, size(cmap, 1));
        plot3(x_path_all{it}, y_path_all{it}, z_path_all{it}, ...
            'Color', cmap(ci,:), 'LineWidth', 0.8);
    end

    markerStyles = {'o', 's', 'd', '^', 'v'};
    for ip = 1:numel(z_projection_planes)
        [xs, ys, ~, ~, qs] = sample_flux_tubes_at_z( ...
            x_path_all, y_path_all, z_path_all, q_trace, z_projection_planes(ip));

        if isempty(xs)
            continue;
        end

        markerStyle = markerStyles{min(ip, numel(markerStyles))};
        scatter3(xs, ys, z_projection_planes(ip) * ones(size(xs)), ...
            18, qs, markerStyle, 'filled', ...
            'MarkerEdgeColor', 'k', 'LineWidth', 0.15);
    end

    colormap(cmap);
    if qmax > qmin
        caxis([qmin qmax]);
    else
        dq = max(abs(qmin), 1) * 1e-6;
        caxis([qmin-dq qmax+dq]);
    end

    cb = colorbar;
    ylabel(cb, 'q_{source} [W/m^2]');

    xlabel('x [m]');
    ylabel('y [m]');
    zlabel('z [m]');
    title('3D flux tubes carrying window-derived heat flux');

    axis equal;
    view(-35, 22);
    camlight headlight;
    lighting gouraud;

    rView = max([geom.rView, max(abs([cellfun(@max_abs_or_zero, x_path_all); ...
                                      cellfun(@max_abs_or_zero, y_path_all)]))]);
    if ~isfinite(rView) || rView <= 0
        rView = 0.25;
    end

    xlim(rView * [-1 1]);
    ylim(rView * [-1 1]);
    zlim([min(z_projection_planes) max(z_projection_planes)]);

    text(0.055, 0, z_source, ' source', ...
        'Color', [0.2 0.2 0.2], 'FontWeight', 'bold');
    text(0.055, 0, z_target, ' target', ...
        'Color', [0 0 0.75], 'FontWeight', 'bold');

    plot_mpex_flux_tubes_RZ( ...
        x_path_all, y_path_all, z_path_all, q_trace, ...
        z_projection_planes, z_projection_labels, coilGeometryFile);
end

function plot_mpex_flux_tubes_RZ( ...
    x_path_all, y_path_all, z_path_all, q_trace, ...
    z_projection_planes, z_projection_labels, coilGeometryFile)

    if isempty(x_path_all) || isempty(q_trace) || ~any(isfinite(q_trace))
        return;
    end

    geom = load_mpex_plot_geometry(coilGeometryFile);
    cmap = get_heat_colormap(256);
    qmin = min(q_trace(:), [], 'omitnan');
    qmax = max(q_trace(:), [], 'omitnan');

    figure('Color','w','Position',[80 80 1550 850]);
    hold on;
    grid on;
    box on;

    plot_mpex_device_RZ(geom, z_projection_planes, z_projection_labels);

    for it = 1:numel(z_path_all)
        if isempty(z_path_all{it})
            continue;
        end

        ci = color_index(q_trace(it), qmin, qmax, size(cmap, 1));
        rpath = hypot(x_path_all{it}, y_path_all{it});

        plot(z_path_all{it}, rpath, ...
            'Color', cmap(ci,:), ...
            'LineWidth', 0.55, ...
            'HandleVisibility', 'off');
        plot(z_path_all{it}, -rpath, ...
            'Color', cmap(ci,:), ...
            'LineWidth', 0.55, ...
            'HandleVisibility', 'off');
    end

    markerStyles = {'o', 's', 'd', '^', 'v'};
    for ip = 1:numel(z_projection_planes)
        [~, ~, rs, ~, qs] = sample_flux_tubes_at_z( ...
            x_path_all, y_path_all, z_path_all, q_trace, z_projection_planes(ip));

        if isempty(rs)
            continue;
        end

        markerStyle = markerStyles{min(ip, numel(markerStyles))};
        scatter(z_projection_planes(ip) * ones(size(rs)), rs, ...
            26, qs, markerStyle, 'filled', ...
            'MarkerEdgeColor', 'k', ...
            'DisplayName', z_projection_labels{ip});
        scatter(z_projection_planes(ip) * ones(size(rs)), -rs, ...
            26, qs, markerStyle, 'filled', ...
            'MarkerEdgeColor', 'k', ...
            'HandleVisibility', 'off');
    end

    colormap(cmap);
    if qmax > qmin
        caxis([qmin qmax]);
    end

    xlabel('z [m]');
    ylabel('r [m]');
    title('MPEX geometry with traced flux-tube field lines');
    xlim([min(z_projection_planes) max(z_projection_planes)]);
    ylim(1.05 * geom.rView * [-1 1]);

    cb = colorbar;
    ylabel(cb, 'q_{source} [W/m^2]');
    legend('Location','bestoutside');
end

function geom = plot_mpex_device_3D(coilGeometryFile, z_projection_planes, z_projection_labels)

    geom = load_mpex_plot_geometry(coilGeometryFile);

    plot_vessel_profile_3D(geom.vessel_z, geom.vessel_r, [0.35 0.35 0.35], 0.055);
    plot_annular_band_3D(geom.helicon_z, geom.helicon_r_inner, geom.helicon_r_outer, ...
        [0 0 1], 0.30);
    plot_annular_band_3D(geom.limiter_z, geom.limiter_r_inner, geom.limiter_r_outer, ...
        [0 0.65 0], 0.32);
    plot_annular_band_3D(geom.skimmer_z, geom.skimmer_r_inner, geom.skimmer_r_outer, ...
        [0 0 0], 0.18);

    plot_coils_3D_from_geometry(geom);
    plot_mpex_projection_planes_3D(geom, z_projection_planes, z_projection_labels);
end

function geom = load_mpex_plot_geometry(coilGeometryFile)

    coilTable = [];
    if exist(coilGeometryFile, 'file')
        try
            coilTable = readtable(coilGeometryFile);
        catch ME
            warning('Could not read %s for MPEX plot geometry: %s', coilGeometryFile, ME.message);
        end
    end

    geom = build_mpex_plot_geometry(coilTable);
end

function geom = build_mpex_plot_geometry(coilTable)

    default_z = [0.9881; 1.2981; 1.6282; 1.8642; 2.1902; 2.3882; ...
                 2.9442; 3.1092; 3.3887; 3.5919; 3.7824; 3.9729; 4.2904];
    default_dz = 0.0979 * ones(size(default_z));
    default_r_inner = 0.1221 * ones(size(default_z));
    default_r_outer = 0.1785 * ones(size(default_z));
    default_ps = {'PS1'; 'TR1'; 'PS3'; 'PS3'; 'X'; 'PS1'; ...
                  'TR2'; 'TR2'; 'PS2'; 'PS2'; 'PS2'; 'PS2'; 'PS2'};

    useDefault = true;

    if ~isempty(coilTable)
        names = coilTable.Properties.VariableNames;
        requiredNames = {'z', 'dz', 'r_inner', 'r_outer', 'ps'};
        if all(ismember(requiredNames, names))
            useDefault = false;
            geom.coil_z = double(coilTable.z(:));
            geom.coil_dz = double(coilTable.dz(:));
            geom.coil_r_inner = double(coilTable.r_inner(:));
            geom.coil_r_outer = double(coilTable.r_outer(:));
            geom.coil_ps = cell(numel(geom.coil_z), 1);

            for j = 1:numel(geom.coil_z)
                geom.coil_ps{j} = table_value_as_text(coilTable.ps(j));
            end
        end
    end

    if useDefault
        geom.coil_z = default_z;
        geom.coil_dz = default_dz;
        geom.coil_r_inner = default_r_inner;
        geom.coil_r_outer = default_r_outer;
        geom.coil_ps = default_ps;
    end

    in2m = 0.0254;

    geom.rDump = 15.75 * in2m / 2;
    geom.zDump = 0.5;
    geom.rTarget = 0.045;

    zCC1 = geom.coil_z(6) + 0.5 * geom.coil_dz(6);
    zCC2 = geom.coil_z(7) - 0.5 * geom.coil_dz(7);
    rCC  = 24 * in2m / 2;

    geom.rVac1 = 5.834 * in2m / 2;
    geom.rVac2 = 19.25 * in2m / 2;
    geom.rVac3 = 4.272 * in2m;
    zVac3 = geom.coil_z(end) + 0.5 * geom.coil_dz(end);

    L_window = 11.8 * in2m;
    geom.helicon_r_inner = 4.95 * in2m / 2;
    geom.helicon_r_outer = geom.rVac1;
    z1 = 0.5 * (geom.coil_z(3) + geom.coil_z(4)) - L_window / 2;
    z2 = 0.5 * (geom.coil_z(3) + geom.coil_z(4)) + L_window / 2;
    geom.helicon_z = [z1 z2];

    limiterLength = 30e-2;
    limiterWidth = 3e-3;
    z1 = geom.helicon_z(2) + 1e-2;
    z2 = z1 + limiterLength;
    geom.limiter_r_inner = 2.5 * in2m - limiterWidth;
    geom.limiter_r_outer = geom.rVac1;
    geom.limiter_z = [z1 z2];

    geom.skimmer_r_inner = 0.07 / 2;
    geom.skimmer_r_outer = geom.rVac1;
    z1 = geom.coil_z(5) + 0.0702 - 0.5e-2;
    z2 = geom.coil_z(5) + 0.0702 + 0.5e-2;
    geom.skimmer_z = [z1 z2];

    geom.vessel_z = [geom.zDump, geom.zDump, geom.zDump+0.2, geom.zDump+0.2, ...
                     zCC1, zCC1, zCC2, zCC2, zVac3];
    geom.vessel_r = [0, geom.rDump, geom.rDump, geom.rVac1, ...
                     geom.rVac1, rCC, rCC, geom.rVac3, geom.rVac3];

    geom.rView = max([geom.rDump, rCC, geom.coil_r_outer(:).']);
end

function plot_vessel_profile_3D(zTop, rTop, colorSpec, alphaVal)

    theta = linspace(0, 2*pi, 180);

    for k = 1:numel(zTop)-1
        z1 = zTop(k);
        z2 = zTop(k+1);
        R1 = rTop(k);
        R2 = rTop(k+1);

        if max(abs([R1 R2])) < 1e-12
            continue;
        end

        [TH, TT] = meshgrid(theta, linspace(0, 1, 18));
        ZZ = z1 + TT * (z2 - z1);
        RR = R1 + TT * (R2 - R1);

        surf(RR .* cos(TH), RR .* sin(TH), ZZ, ...
            'FaceColor', colorSpec, ...
            'FaceAlpha', alphaVal, ...
            'EdgeColor', 'none');

        if R1 > 1e-12
            plot3(R1*cos(theta), R1*sin(theta), z1*ones(size(theta)), ...
                'Color', colorSpec, 'LineWidth', 1.2);
        end
        if R2 > 1e-12
            plot3(R2*cos(theta), R2*sin(theta), z2*ones(size(theta)), ...
                'Color', colorSpec, 'LineWidth', 1.2);
        end
    end
end

function plot_annular_band_3D(zSpan, Rin, Rout, colorSpec, alphaVal)

    theta = linspace(0, 2*pi, 150);
    plot_annular_cylinder_3D(Rin, Rout, zSpan(1), zSpan(2), theta, colorSpec, alphaVal);
    plot_coil_edges_3D(Rin, Rout, zSpan(1), zSpan(2), theta, colorSpec);
end

function plot_mpex_projection_planes_3D(geom, z_projection_planes, z_projection_labels)

    for ip = 1:numel(z_projection_planes)
        label = z_projection_labels{ip};
        labelLower = lower(label);

        if ~isempty(strfind(labelLower, 'dump')) %#ok<STREMP>
            R = geom.rDump;
            c = [1 0 0];
        elseif ~isempty(strfind(labelLower, 'helicon')) %#ok<STREMP>
            R = geom.rVac1;
            c = [0 0 1];
        elseif ~isempty(strfind(labelLower, 'target')) %#ok<STREMP>
            R = geom.rTarget;
            c = [0 0 0.75];
        else
            R = geom.rVac1;
            c = [0.15 0.15 0.15];
        end

        plot_plane_grid_3D(z_projection_planes(ip), R, c, label);
    end
end

function plot_mpex_device_RZ(geom, z_projection_planes, z_projection_labels)

    plot_vessel_profile_RZ(geom.vessel_z, geom.vessel_r, [0.2 0.2 0.2], 2.0);
    plot_annular_band_RZ(geom.helicon_z, geom.helicon_r_inner, geom.helicon_r_outer, ...
        [0 0 1], 0.28);
    plot_annular_band_RZ(geom.limiter_z, geom.limiter_r_inner, geom.limiter_r_outer, ...
        [0 0.65 0], 0.28);
    plot_annular_band_RZ(geom.skimmer_z, geom.skimmer_r_inner, geom.skimmer_r_outer, ...
        [0 0 0], 0.18);
    plot_coils_RZ_from_geometry(geom);

    yline(0, 'k:', 'HandleVisibility', 'off');

    for ip = 1:numel(z_projection_planes)
        label = z_projection_labels{ip};
        labelLower = lower(label);
        if ~isempty(strfind(labelLower, 'dump')) %#ok<STREMP>
            c = [1 0 0];
        elseif ~isempty(strfind(labelLower, 'helicon')) %#ok<STREMP>
            c = [0 0 1];
        elseif ~isempty(strfind(labelLower, 'target')) %#ok<STREMP>
            c = [0 0 0.75];
        else
            c = [0.15 0.15 0.15];
        end

        xline(z_projection_planes(ip), '--', label, ...
            'Color', c, 'LineWidth', 1.4, 'HandleVisibility', 'off');
    end
end

function plot_vessel_profile_RZ(zTop, rTop, colorSpec, lineWidth)

    plot(zTop, rTop, ...
        'Color', colorSpec, ...
        'LineWidth', lineWidth, ...
        'HandleVisibility', 'off');
    plot(zTop, -rTop, ...
        'Color', colorSpec, ...
        'LineWidth', lineWidth, ...
        'HandleVisibility', 'off');
end

function plot_annular_band_RZ(zSpan, Rin, Rout, colorSpec, alphaVal)

    patch([zSpan(1) zSpan(2) zSpan(2) zSpan(1)], ...
          [Rin Rin Rout Rout], colorSpec, ...
          'FaceAlpha', alphaVal, ...
          'EdgeColor', colorSpec, ...
          'LineWidth', 1.0, ...
          'HandleVisibility', 'off');
    patch([zSpan(1) zSpan(2) zSpan(2) zSpan(1)], ...
          [-Rin -Rin -Rout -Rout], colorSpec, ...
          'FaceAlpha', alphaVal, ...
          'EdgeColor', colorSpec, ...
          'LineWidth', 1.0, ...
          'HandleVisibility', 'off');
end

function plot_coils_RZ_from_geometry(geom)

    for j = 1:numel(geom.coil_z)
        z1 = geom.coil_z(j) - 0.5 * geom.coil_dz(j);
        dZ = geom.coil_dz(j);
        dR = geom.coil_r_outer(j) - geom.coil_r_inner(j);
        c = coil_color_mpex(geom.coil_ps{j});

        rectangle('Position', [z1, geom.coil_r_inner(j), dZ, dR], ...
            'FaceColor', c, ...
            'EdgeColor', c, ...
            'LineWidth', 0.8, ...
            'HandleVisibility', 'off');
        rectangle('Position', [z1, -geom.coil_r_outer(j), dZ, dR], ...
            'FaceColor', c, ...
            'EdgeColor', c, ...
            'LineWidth', 0.8, ...
            'HandleVisibility', 'off');
    end
end

function plot_plane_grid_3D(z0, Rmax, colorSpec, label)

    theta = linspace(0, 2*pi, 160);

    for rr = linspace(0, Rmax, 6)
        plot3(rr*cos(theta), rr*sin(theta), z0*ones(size(theta)), ...
            'Color', colorSpec, 'LineWidth', 0.8);
    end

    for th = linspace(0, 2*pi, 12)
        plot3([0 Rmax*cos(th)], [0 Rmax*sin(th)], [z0 z0], ...
            'Color', colorSpec, 'LineWidth', 0.45);
    end

    text(0.72*Rmax, 0, z0, sprintf(' %s', label), ...
        'Color', colorSpec, 'FontWeight', 'bold');
end

function plot_coils_3D_from_geometry(geom)

    theta = linspace(0, 2*pi, 90);

    for j = 1:numel(geom.coil_z)
        z1 = geom.coil_z(j) - 0.5 * geom.coil_dz(j);
        z2 = geom.coil_z(j) + 0.5 * geom.coil_dz(j);
        c = coil_color_mpex(geom.coil_ps{j});

        plot_annular_cylinder_3D(geom.coil_r_inner(j), geom.coil_r_outer(j), ...
            z1, z2, theta, c, 0.28);
        plot_coil_edges_3D(geom.coil_r_inner(j), geom.coil_r_outer(j), ...
            z1, z2, theta, c);
    end
end

function plot_annular_cylinder_3D(Rin, Rout, z1, z2, theta, faceColor, alphaVal)

    [TH, ZZ] = meshgrid(theta, [z1 z2]);

    Xo = Rout * cos(TH);
    Yo = Rout * sin(TH);
    Xi = Rin * cos(TH);
    Yi = Rin * sin(TH);

    surf(Xo, Yo, ZZ, ...
        'FaceColor', faceColor, 'EdgeColor', 'none', 'FaceAlpha', alphaVal);
    surf(Xi, Yi, ZZ, ...
        'FaceColor', faceColor, 'EdgeColor', 'none', 'FaceAlpha', alphaVal);

    [TH2, RR] = meshgrid(theta, [Rin Rout]);

    Xcap = RR .* cos(TH2);
    Ycap = RR .* sin(TH2);

    surf(Xcap, Ycap, z1*ones(size(Xcap)), ...
        'FaceColor', faceColor, 'EdgeColor', 'none', 'FaceAlpha', alphaVal);
    surf(Xcap, Ycap, z2*ones(size(Xcap)), ...
        'FaceColor', faceColor, 'EdgeColor', 'none', 'FaceAlpha', alphaVal);
end

function plot_coil_edges_3D(Rin, Rout, z1, z2, theta, colorSpec)

    for R = [Rin Rout]
        plot3(R*cos(theta), R*sin(theta), z1*ones(size(theta)), ...
            'Color', colorSpec, 'LineWidth', 0.75);
        plot3(R*cos(theta), R*sin(theta), z2*ones(size(theta)), ...
            'Color', colorSpec, 'LineWidth', 0.75);
    end

    for th = linspace(0, 2*pi, 12)
        plot3([Rin Rout]*cos(th), [Rin Rout]*sin(th), [z1 z1], ...
            'Color', colorSpec, 'LineWidth', 0.45);
        plot3([Rin Rout]*cos(th), [Rin Rout]*sin(th), [z2 z2], ...
            'Color', colorSpec, 'LineWidth', 0.45);
    end
end

function [xs, ys, rs, ths, qs] = sample_flux_tubes_at_z( ...
    x_path_all, y_path_all, z_path_all, q_trace, zslice)

    xs = [];
    ys = [];
    rs = [];
    ths = [];
    qs = [];

    for it = 1:numel(z_path_all)
        zpath = z_path_all{it};

        if isempty(zpath)
            continue;
        end

        zmin = min(zpath);
        zmax = max(zpath);

        if zslice < zmin || zslice > zmax
            continue;
        end

        xpath = x_path_all{it};
        ypath = y_path_all{it};

        xq = interp1(zpath, xpath, zslice, 'linear');
        yq = interp1(zpath, ypath, zslice, 'linear');

        if ~isfinite(xq) || ~isfinite(yq)
            continue;
        end

        rq = hypot(xq, yq);
        thq = mod(atan2d(yq, xq), 360);

        xs(end+1,1) = xq; %#ok<AGROW>
        ys(end+1,1) = yq; %#ok<AGROW>
        rs(end+1,1) = rq; %#ok<AGROW>
        ths(end+1,1) = thq; %#ok<AGROW>
        qs(end+1,1) = q_trace(it); %#ok<AGROW>
    end
end

function ci = color_index(value, vmin, vmax, nColor)

    if ~isfinite(value) || vmax <= vmin
        ci = 1;
    else
        ci = round(1 + (nColor-1) * (value-vmin) / (vmax-vmin));
        ci = max(1, min(nColor, ci));
    end
end

function cmap = get_heat_colormap(nColor)

    if exist('turbo', 'file') || exist('turbo', 'builtin')
        cmap = turbo(nColor);
    else
        cmap = parula(nColor);
    end
end

function c = coil_color_mpex(psValue)

    psString = upper(strtrim(table_value_as_text(psValue)));

    if strcmp(psString, 'PS1')
        c = [0.9 0 0];
    elseif strcmp(psString, 'PS2')
        c = [0.75 0 0.75];
    elseif strcmp(psString, 'PS3')
        c = [0 0.65 0.9];
    elseif strcmp(psString, 'TR1')
        c = [0 0 1];
    elseif strcmp(psString, 'TR2')
        c = [0 0.65 0];
    else
        c = [0.62 0.62 0.62];
    end
end

function txt = table_value_as_text(value)

    if iscell(value)
        value = value{1};
    end

    if ischar(value)
        txt = value;
    elseif isnumeric(value)
        txt = num2str(value);
    else
        txt = char(value);
    end

    if isempty(txt)
        txt = '';
    end
end

function value = max_abs_or_zero(x)

    if isempty(x)
        value = 0;
    else
        value = max(abs(x(:)));
        if ~isfinite(value)
            value = 0;
        end
    end
end

function [x_grid, y_grid, q_map, q_lm, hit_ok, x_hit_lm, y_hit_lm] = rasterize_centerline_projection_heat_map( ...
    R_LM, THETA_LM_DEG, z_source, z_plane, FBr, FBt, FBz, r_grid, z_grid, ...
    dz_trace, nStepsMax, stop_if_outside_grid, q_center_lm, nX, nY, pad)

    [nL, nM] = size(R_LM);
    nPatches = nL * nM;

    x_hit_vec = NaN(nPatches, 1);
    y_hit_vec = NaN(nPatches, 1);
    q_vec = q_center_lm(:);

    R_vec = R_LM(:);
    THETA_vec = THETA_LM_DEG(:);

    parfor ii = 1:nPatches
        if ~isfinite(q_vec(ii)) || ~isfinite(R_vec(ii)) || ~isfinite(THETA_vec(ii))
            continue;
        end

        [ok, xhit, yhit] = trace_point_to_target( ...
            R_vec(ii), THETA_vec(ii), z_source, FBr, FBt, FBz, ...
            r_grid, z_grid, z_plane, dz_trace, nStepsMax, stop_if_outside_grid);

        if ok
            x_hit_vec(ii) = xhit;
            y_hit_vec(ii) = yhit;
        end
    end

    x_hit_lm = reshape(x_hit_vec, nL, nM);
    y_hit_lm = reshape(y_hit_vec, nL, nM);
    q_lm = NaN(nL, nM);
    hit_ok = isfinite(x_hit_lm) & isfinite(y_hit_lm) & isfinite(q_center_lm);
    q_lm(hit_ok) = q_center_lm(hit_ok);

    valid = isfinite(x_hit_vec) & isfinite(y_hit_vec) & isfinite(q_vec);

    if nnz(valid) < 3
        x_grid = linspace(-pad, pad, nX);
        y_grid = linspace(-pad, pad, nY);
        q_map = NaN(nY, nX);
        return;
    end

    xv = x_hit_vec(valid);
    yv = y_hit_vec(valid);
    qv = q_vec(valid);

    x_grid = linspace(min(xv)-pad, max(xv)+pad, nX);
    y_grid = linspace(min(yv)-pad, max(yv)+pad, nY);
    [XG, YG] = meshgrid(x_grid, y_grid);

    q_map = griddata(xv, yv, qv, XG, YG, 'linear');
    q_nearest = griddata(xv, yv, qv, XG, YG, 'nearest');

    rHit = hypot(xv, yv);
    rGrid = hypot(XG, YG);
    rMin = max(0, min(rHit) - pad);
    rMax = max(rHit) + pad;
    footprintMask = rGrid >= rMin & rGrid <= rMax;

    fillMask = footprintMask & ~isfinite(q_map);
    q_map(fillMask) = q_nearest(fillMask);
    q_map(~footprintMask) = NaN;
end

function [x_plane_c, y_plane_c, z_plane_c, patch_ok_plane, fail_corner_plane] = trace_patch_corners_to_plane( ...
    xsrc_c, ysrc_c, zsrc_c, z_plane, FBr, FBt, FBz, r_grid, z_grid, dz_trace, nStepsMax, stop_if_outside_grid)

    [nL, nM, ~] = size(xsrc_c);
    nPatches = nL * nM;

    x_plane_c = NaN(nL, nM, 4);
    y_plane_c = NaN(nL, nM, 4);
    z_plane_c = NaN(nL, nM, 4);
    patch_ok_plane = false(nL, nM);
    fail_corner_plane = NaN(nL, nM);

    x_plane_flat = NaN(nPatches, 4);
    y_plane_flat = NaN(nPatches, 4);
    z_plane_flat = NaN(nPatches, 4);
    fail_flat = NaN(nPatches, 1);

    xsrc_flat = reshape(xsrc_c, nPatches, 4);
    ysrc_flat = reshape(ysrc_c, nPatches, 4);
    zsrc_flat = reshape(zsrc_c, nPatches, 4);

    parfor ii = 1:nPatches
        ok_all = true;
        xhit_row = NaN(1, 4);
        yhit_row = NaN(1, 4);
        zhit_row = NaN(1, 4);
        fc = NaN;

        for ic = 1:4
            rc  = hypot(xsrc_flat(ii,ic), ysrc_flat(ii,ic));
            thc = mod(atan2d(ysrc_flat(ii,ic), xsrc_flat(ii,ic)), 360);
            zc  = zsrc_flat(ii,ic);

            [ok, xhit, yhit, zhit] = trace_point_to_target( ...
                rc, thc, zc, FBr, FBt, FBz, r_grid, z_grid, z_plane, ...
                dz_trace, nStepsMax, stop_if_outside_grid);

            if ~ok
                ok_all = false;
                fc = ic;
                break;
            end

            xhit_row(ic) = xhit;
            yhit_row(ic) = yhit;
            zhit_row(ic) = zhit;
        end

        if ok_all
            x_plane_flat(ii,:) = xhit_row;
            y_plane_flat(ii,:) = yhit_row;
            z_plane_flat(ii,:) = zhit_row;
        else
            fail_flat(ii) = fc;
        end
    end

    for ii = 1:nPatches
        [il, im] = ind2sub([nL, nM], ii);
        if all(isfinite(x_plane_flat(ii,:)))
            x_plane_c(il,im,:) = x_plane_flat(ii,:);
            y_plane_c(il,im,:) = y_plane_flat(ii,:);
            z_plane_c(il,im,:) = z_plane_flat(ii,:);
            patch_ok_plane(il,im) = true;
        else
            fail_corner_plane(il,im) = fail_flat(ii);
        end
    end
end

function [A_plane_lm, q_plane_lm] = compute_plane_heat_flux_lm( ...
    x_plane_c, y_plane_c, patch_ok_plane, P_tube_lm)

    [nL, nM, ~] = size(x_plane_c);
    A_plane_lm = NaN(nL, nM);
    q_plane_lm = NaN(nL, nM);

    for il = 1:nL
        for im = 1:nM
            if ~patch_ok_plane(il,im) || ~isfinite(P_tube_lm(il,im))
                continue;
            end

            xv = squeeze(x_plane_c(il,im,:));
            yv = squeeze(y_plane_c(il,im,:));

            if any(~isfinite(xv)) || any(~isfinite(yv))
                continue;
            end

            A_poly = polygon_area_xy(xv, yv);
            if A_poly < 1e-12
                continue;
            end

            A_plane_lm(il,im) = A_poly;
            q_plane_lm(il,im) = P_tube_lm(il,im) / A_poly;
        end
    end
end

function [x_grid, y_grid, q_map, q_count] = rasterize_plane_heat_flux_map( ...
    x_plane_c, y_plane_c, patch_ok_plane, q_plane_lm, nX, nY, pad)

    finiteX = x_plane_c(isfinite(x_plane_c));
    finiteY = y_plane_c(isfinite(y_plane_c));

    if isempty(finiteX) || isempty(finiteY)
        x_grid = linspace(-pad, pad, nX);
        y_grid = linspace(-pad, pad, nY);
        q_map = NaN(nY, nX);
        q_count = zeros(nY, nX);
        return;
    end

    x_grid = linspace(min(finiteX)-pad, max(finiteX)+pad, nX);
    y_grid = linspace(min(finiteY)-pad, max(finiteY)+pad, nY);
    [XG, YG] = meshgrid(x_grid, y_grid);

    q_sum = zeros(nY, nX);
    q_count = zeros(nY, nX);

    [nL, nM, ~] = size(x_plane_c);
    for il = 1:nL
        for im = 1:nM
            if ~patch_ok_plane(il,im) || ~isfinite(q_plane_lm(il,im))
                continue;
            end

            xv = squeeze(x_plane_c(il,im,:));
            yv = squeeze(y_plane_c(il,im,:));

            in = inpolygon(XG, YG, xv, yv);
            q_sum(in) = q_sum(in) + q_plane_lm(il,im);
            q_count(in) = q_count(in) + 1;
        end
    end

    q_map = NaN(nY, nX);
    mask = q_count > 0;
    q_map(mask) = q_sum(mask) ./ q_count(mask);
end

function A_poly = polygon_area_xy(xv, yv)
    nv = numel(xv);
    A_poly = 0;

    for kv = 1:nv
        kn = mod(kv, nv) + 1;
        A_poly = A_poly + xv(kv)*yv(kn) - xv(kn)*yv(kv);
    end

    A_poly = 0.5 * abs(A_poly);
end
